services:
  postgres:
    image: postgres:16
    container_name: company_postgres
    environment:
      POSTGRES_DB: company
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - company-network

  teacher-service:
    build:
      context: ./teacherrvp
      dockerfile: dockerfile
    container_name: teacher-service
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/company
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - company-network

  report-service:
    build:
      context: ./report-service
      dockerfile: dockerfile
    container_name: report-service
    ports:
      - "8082:8082"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/company
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - company-network

  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      TEACHER_SERVICE_URL: http://teacher-service:8081
      REPORT_SERVICE_URL: http://report-service:8082
    depends_on:
      - teacher-service
      - report-service
    networks:
      - company-network

networks:
  company-network:
    driver: bridge

volumes:
  postgres_data: